### ISSUE TITLE
Urgent image exports no longer working

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#112]
@arunge image export no longer working (app crashes). Give priority to fix this.

**Comment by arunge** [comment]
@isomemo This seems to be a problem with the current docker image of the beta version: when testing the local docker installation I receive errors when trying to download a plot:

![image](https://user-images.githubusercontent.com/16759098/223399017-3d3676fd-10c7-49b5-8a1b-1a3003c5cb5e.png)

Running the app (main & beta) in R locally does not lead to any issues, all is working as expected.

Running the main version with docker only gives a warning when exporting a plot, but the app did not crash:

![image](https://user-images.githubusercontent.com/16759098/223400327-1b258100-f231-4d1a-9564-2f89f49d151a.png)

This has most likely to do with changes of the base-image because of the upgrade to R.4.2.2 last week. We are checking what is going on there. Thanks for you patience!

**Comment by arunge** [comment]
The issue should be solved now. I downgraded the R version in docker from 4.2.2 to R 4.2.1. Now, the export is working again and the gpt3 feature is also still working: 
- https://isomemoapp.com/app/iso-memo-app-beta  
  ![image](https://user-images.githubusercontent.com/16759098/223516166-c6bff844-9feb-4e0a-b975-c53f0162dfc5.png)
- to use the new version locally, please pull the new version with
  `docker pull ghcr.io/pandora-isomemo/iso-app:beta`

Feel free to test the export! I will check other open bugs on Thursday, thanks for your patience!

**Comment by isomemo** [comment]
@arunge as I understood, you have re-upgraded R, correct? I think that this is the best option.

**Comment by arunge** [comment]
Yes, we had R 4.1.2 before, we jumped to R 4.2.2. but I had to downgrade to R 4.2.1. So in essence we still have an upgrade from R 4.1.2 to R 4.2.1.

**Comment by arunge** [comment]
@isomemo As discussed, I am closing here since this issue [is fixed](https://github.com/Pandora-IsoMemo/iso-app/issues/112#issuecomment-1458640671). Feel free to open new issues in case of problems. Thanks!
