### ISSUE TITLE
Missing border correction for Bayes models

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/iso-app#175]
@mgross There is an issue with the border correction for Bayes models. As you can see in following figure it seems not to be working. This issue was already present in a version from May 2022, so no recent changes are relevant for this bug. Could you please check what is missing, and why the border correction is not working for Bayes models and fix the issue?

![image](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/c6c848c4-9e0a-46ed-89be-d35358556f09)

The data that was used for testing you can find here:
[upload.xlsx](https://github.com/Pandora-IsoMemo/iso-app/files/11801446/upload.xlsx)

For testing you may run the AverageR model (dependent variable ΔR.14C.yr).

@isomemo [asked](https://github.com/Pandora-IsoMemo/iso-app/issues/168#issuecomment-1609047820) if you could check the spherical modelling also?

_From https://github.com/Pandora-IsoMemo/iso-app/issues/168#issuecomment-1607704905_

**Comment by isomemo** [comment]
@mgross I suspect that spherical modelling is also likely not working.

**Comment by isomemo** [comment]
@mgross @arunge 

Great that the spherical option works! However, as you know this can be very computationally demanding. This is why we needed the border correction albeit accepting that this will not perform well at map border regions.

I had tested the Pacific correction a few times in the past and did not notice an issue. Had I known that this was sensitive to the number of iterations, I would have requested a different implementation.

A map centred in the Pacific should be generated in a similar way as a map centred in the Atlantic. After all, this is just a transposition/re-centring along the x-axis.

I probably have asked this previously, but why cannot the following be done:

1) When the user selects the option to centre in the Pacific one keeps using the "Atlantic" modelling approach but one redefines the x variable as x' variable which is simply transposed by 180 degrees (or the equivalent in whatever unit you are using). That is: x' = x +180

2) The modelling is now done on x' as it would be done on x

3) Once the results are generated transpose these back so that display correctly for the Pacific

**Comment by arunge** [comment]
We are checking the option to remove "planar modelling" together with the "border correction", see https://github.com/Pandora-IsoMemo/iso-app/issues/180#issuecomment-1715607128.

**Comment by arunge** [comment]
We are continuing with this issue in:
- https://github.com/Pandora-IsoMemo/iso-app/issues/180

I am closing here.
