### ISSUE TITLE
OperatoR inputs

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#19]
Currently in OperatoR inputs we can select "Data source" and "Select map". However, if I select under "Data source" the option "Save map" no listing is given under "Select Map". This only works if for "Data source". I select "Create map".

I believe that the option the option "Save map" is relative to the creation of maps which is now under of the main menu "Saved maps". This generates considerable confusion. To clarify:

1) In the main menu rename "Saved maps" to "View/create single maps"
2) Under OperatoR. "Data source" as "Create map". In fact, you can drop altogether the first pending list since there is only one single option. You can add the title "OperatoR: map operations". 
3) The progression bar shows "Creating difference map" irrespective of operation being run. This should read only "Creating map"

**Comment by mgross** [comment]
The saved map option under data options is for maps that were already created and saved with OperateR (to re-view them).

**Comment by isomemo** [comment]
Ok! Then we leave it as is but still we need the following:

In the main menu rename "Saved maps" to "View/create single maps" since the creation of "numeric" maps is done under this menu. It is not only for viewing.

Under this menu, the option to create a rectangle (now named square, please correct naming) and given input boxes for lat/long of upper left/lower right rectangle. Now showing option for circle.

In OperatoR, the progression bar shows "Creating difference map" irrespective of operation being run. This should read only "Creating map"

**Comment by jroachell15** [comment]
@mgross have you already helped @isomemo on this issue or should i make the name changes?

**Comment by mgross** [comment]
@jroachell15 If you can do this I would be grateful

**Comment by jroachell15** [comment]
@isomemo 

i have changed the `saved maps` to `View single map`:
![image](https://user-images.githubusercontent.com/73887426/175028203-452d5146-3f02-4a27-ba3b-d84a43609c9a.png)

also 

now when performing the run, the progressing the bar shows now "Generating map" instead of "Generating difference map"


is there anything else you want to change?

**Comment by isomemo** [comment]
@jroachell15 

In the main menu:

![image](https://user-images.githubusercontent.com/46485054/175034822-cae5ac3a-109d-4bc7-aaea-baf9b372f09a.png)

Rename "Saved maps" to "Saved/Create maps"

Once you select the above you have the following inputs:

![image](https://user-images.githubusercontent.com/46485054/175035242-ee7b5ef6-80e5-46b7-86c6-4832563408e1.png)

If I select "region - circle" it makes sense then to select a "Radius in km" and "Set Latitude center" and "Set Longitude of center". That is, it draws a circle of a certain radius for a selected centre. However, I I select the option "region - square" I have the same options. Obviously, I cannot set a radius for a square. So, first please clarify how is the square is being drawn? Once I know this, we can rename the inputs accordingly.

Also, for the above, instead of a scroller to select the "Radius in km" please have an input box.

Under OperatoR:

![image](https://user-images.githubusercontent.com/46485054/175036538-6f463c31-58ce-4a8c-86ce-4beb30dc1871.png)

The option "Saved maps", I noticed, only loads maps saved under OperatoR, so best to rename this as "Load OperatoR map" instead of "View single map" as previously suggested.

**Comment by jroachell15** [comment]
@isomemo 

> _If I select "region - circle" it makes sense then to select a "Radius in km" and "Set Latitude center" and "Set Longitude of center". That is, it draws a circle of a certain radius for a selected centre. However, I I select the option "region - square" I have the same options. Obviously, I cannot set a radius for a square. So, first please clarify how is the square is being drawn? Once I know this, we can rename the inputs accordingly._
- This I don't know, maybe @arunge has some knowledge on this?

> _Also, for the above, instead of a scroller to select the "Radius in km" please have an input box._
- [ ] this might take some time from Timebank from testing.

- [ ] The option "Saved maps", I noticed, only loads maps saved under OperatoR, so best to rename this as "Load OperatoR map" instead of "View single map" as previously suggested. DONE.

**Comment by mgross** [comment]
It is the side length of the square (at the center latitude)

**Comment by isomemo** [comment]
@mgross @jroachell15 Yes, we will have to change the naming for when a square is selected. However, before doing that, I would like to ask Marcus if it would be easy to have a rectangle instead of square? Can you please show to Jian the code that would need to be updated for a rectangle option? In this, case one would define a width and height.

Also, be it a circle, rectangle, or square have you considered the possibility that a figure, if too large, could cross the lat/long map limits?

**Comment by jroachell15** [comment]
@isomemo 

For this: `change the naming for when a square is selected. However, before doing that, I would like to ask Marcus if it would be easy to have a rectangle instead of square?  Also, be it a circle, rectangle, or square have you considered the possibility that a figure, if too large, could cross the lat/long map limits. For the above, instead of a scroller to select the "Radius in km" please have an input box.`

This seems to be more than just changing names, maybe we start a new issue for this and save that for the next contract or use the timebank? thanks!

**Comment by isomemo** [comment]
@jroachell15 @mgross I was indeed planning to use the support contract to change from square to rectangle implementation but it would be more efficient if Marcus just flags the code where the inputs are given and replies to my previous queries. Then, we can set a different item for the rectangle implementation and complete the renaming.

**Comment by arunge** [comment]
@jroachell15 I merged your current name changes into the beta. Please open a new feature branch for other tasks of this issue.

**Comment by arunge** [comment]
I will check open tasks here and update the ticket next.

**Comment by arunge** [comment]
The code that takes the inputs (1), (2), (3):

![image](https://user-images.githubusercontent.com/16759098/206244951-3e0d882e-d143-4936-ae7b-a9941f927887.png)

can be found here:

https://github.com/Pandora-IsoMemo/iso-app/blob/c860d9585829c536883b5aa9942541370753ab84/R/04-savedMapsModule.R#L28-L46

and `input$userMapType` correspond to:
https://github.com/Pandora-IsoMemo/iso-app/blob/c860d9585829c536883b5aa9942541370753ab84/R/04-savedMapsUI.R#L21

@isomemo Should the slider "Radius in km" be renamed to "Length in km" if "region-square" is selected?


@mgross As far as I understand the formula:
```R
pmax(abs(coord[,2] - input$centerLatitude), abs(coord[,1] - input$centerLongitude)) < input$userRadius / 111
```
 "Radius in km" should be here half of the length of the square side. Is that correct?

If so, one could easily half the value of a new input "Length in km" only for the square case, and will get the same result.

For the additional rectangle option I would create a new ticket afterwards.

**Comment by isomemo** [comment]
@arunge see my comments above. It should be rectangle (not square) and the user would give two coordinates points (upper left and lower right corners). With this is there is no need to input a length.

**Comment by arunge** [comment]
@isomemo as discussed I will implement this and give it into review to @mgross .

**Comment by arunge** [comment]
With [version 23.01.2](https://github.com/Pandora-IsoMemo/iso-app/pull/87#issue-1530898620) of the [isomemo app beta](https://isomemoapp.com/app/iso-memo-app-beta) I added the rectangle option and updated the UI of saved/create map.

@isomemo As discussed, please test the feature since I tested it only with test data and not together with real maps.
Maybe we could rename the button (1) to something like "Create map template"?

![image](https://user-images.githubusercontent.com/16759098/212950938-85dc0060-6794-4bca-9250-56bdf0c3e84f.png)

**Comment by isomemo** [comment]
@arunge I think that probably best to use "Shape vector"

**Comment by arunge** [comment]
@isomemo With[ version 23.03.5](https://github.com/Pandora-IsoMemo/iso-app/pull/121) I added the label (1) to the type column on [beta](https://isomemoapp.com/app/iso-memo-app-beta):

![image](https://user-images.githubusercontent.com/16759098/228537219-3013abbe-2894-4ebf-be67-31c5c62f12de.png)

All is done here.
