### ISSUE TITLE
Issue in exporting GIF

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/iso-app#197]
![Bug Export GIF](https://github.com/Pandora-IsoMemo/iso-app/assets/101706974/53750880-c2f9-4526-9bb6-5a297a8fde0a)
[2023-12-11_15-58-23_model_TimeR.ZIP](https://github.com/Pandora-IsoMemo/iso-app/files/13637388/2023-12-11_15-58-23_model_TimeR.ZIP)

For the attached model (I had to compress it online to attach it here, I hope this works), I cannot export a GIF. I attach the screenshot of the error that I have received. As exporting parameters, I have used -8000 to 2000 (interval), each frame of 500 years, and 1 frame per second.

I have used the Beta online version 23.10.3.

@arunge

**Comment by arunge** [comment]
@CarloCocozza 
The model that you calculated seems to be very large. The calculation time was very long and when trying to upload the model that I saved before, the upload first failed. I had to increase the allowed upload size for the app to be able to upload your model. This is now possible with version 23.12.0.2 of iso-app beta. However, upload online fails most likely because of server related maximal size that can be uploaded.

However, when using the local version (beta) the upload is possible and one can create a gif, which also takes a very long time (> 10 minutes).
![spatio-temporal-average](https://github.com/Pandora-IsoMemo/iso-app/assets/16759098/827d9ebb-9665-44fc-8bdf-57d105f13a3d)

Most likely it will cause problems when trying this online. You can get the beta version with docker with:

```
docker pull ghcr.io/pandora-isomemo/iso-app:beta
```
and start it just with:
```
docker run -p 3838:3838 ghcr.io/pandora-isomemo/iso-app:beta
```
Hopefully, this helps when trying to create gifs from large models!
