### ISSUE TITLE
Error when showing only Centroids in KernelTimeR

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/iso-app#205]
[2024-04-25_19-38-21_model_KernelTimeR.zip](https://github.com/Pandora-IsoMemo/iso-app/files/15118682/2024-04-25_19-38-21_model_KernelTimeR.zip)
![Bug Centroids](https://github.com/Pandora-IsoMemo/iso-app/assets/101706974/e338be22-887b-4a7b-8b01-b00a8a5f6aea)
For the attached model, the following error appears when in KernelTimeR I select the option "Show only centroids".

@arunge

**Comment by arunge** [comment]
@CarloCocozza The issue from [above](https://github.com/Pandora-IsoMemo/iso-app/issues/205#issue-2264169259) was also fixed with [version 24.04.0](https://github.com/Pandora-IsoMemo/iso-app/pull/208) on the [beta app](https://isomemoapp.com/app/iso-memo-app-beta). The color assignment for cluster centers was not working correctly. This is fixed now. Feel free to test different settings.
I am also pushing the fix to the [main app](https://isomemoapp.com/app/iso-memo-app), where the new version will be available soon.  I am closing here.
