### ISSUE TITLE
[MPI_erweiterung_priority_054]: Pandora/Isomemo. Save and load files fully describing models plus a text describing model

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/iso-app#3]
Original ticket: https://github.com/INWT/mpi-iso-app/issues/247

User will be able to save and load files fully describing models plus a text describing the model (text entered by user before saving) for apps ReSources /OsteoBioR /Bpred/ IsoMemo models. The saved files should be loadable directly into R so that a user may execute the models within the R environment (this should include the description of the different functions accessible via help). The user will also be able to load files available from a directory online (for the Desktop version of the apps this will require an internet connection). The files for each app/model will be stored in a separate online directory. These individual directories will be contained within a single directory. In the app interface files stored in an online directory are displayed in a pending list showing their names (without extension). The user selects one of these and presses load to load it.

Pandora/IsoMemo models (current and those being developed): all needs to be implemented. There should be a directory for each Pandora/IsoMemo model. Furthermore, in these cases the files in the directory are not R files but data files with pre-defined column names. Add a new option to load these files under “Data Source” with the title “Online file”. In this case, no need for a text describing the model. However, to be added an export option within each Pandora/IsoMemo model that provides the RData file that can be used in R.

see https://github.com/INWT/mpi-bpred/issues/45#issuecomment-1012092039
and https://github.com/INWT/mpi-bpred/blob/cc9612c69e893e57dad3bdb1f814ec0fd582e5e7/inst/app/server.R#L587-L607

**Comment by arunge** [comment]
It is planed to implement this feature step by step, optimally after the refactoring within #34.
The isomemo app provides several models and thus we have different model outputs to be downloaded/uploaded. We need to implement the structure for a secure update of 
- model results and 
- user inputs 

after a model object was uploaded dependent on the respective model object.

**Comment by arunge** [comment]
On hold until #34 was finished and the restructuring within #69

**Comment by arunge** [comment]
@isomemo With [version 23.04.1 of the iso-app](https://github.com/Pandora-IsoMemo/iso-app/pull/128) I could add the option to up- and download a model object (containing user inputs, data and model output) to each of the modeling tabs:

![image](https://user-images.githubusercontent.com/16759098/230020726-e714f6a5-9373-4679-933b-3d680072226d.png)

However, we must discuss the following from [above](https://github.com/Pandora-IsoMemo/iso-app/issues/3#issue-1138384568) since the implementation differs slightly from the task:

> Furthermore, in these cases the files in the directory are not R files but data files with pre-defined column names. Add a new option to load these files under “Data Source” with the title “Online file”. In this case, no need for a text describing the model. However, to be added an export option within each Pandora/IsoMemo model that provides the RData file that can be used in R.

Currently, when uploading a model object the table in the tab "Data" will not be updated. Updating also the table would mean we had to reset the content of all other modelling tabs. I am not sure if this should be the desired behavior. Please let us discuss how to solve this.

**Comment by arunge** [comment]
As discussed, we keep the tab "data" independent from the "model" tabs: That is, when uploading a model, the data tab will not be updated. This avoids confusion when uploading several models and switching between modelling tabs. 

So nothing must be done here and the task is finished.
