### ISSUE TITLE
Non uniform point size

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#44]
@arunge 

In the IsoMemo skin I selected all databases and produced a map. I set the point size at 34km but as you can see from the figure below the point size is not uniform (the trend seems to be that points become larger as one moves north and vice-versa, this suggests some issue with the size calculation not accounting for latitude)

![image](https://user-images.githubusercontent.com/46485054/176658256-4b8b4df3-90e3-492d-826f-5b24491c6ee0.png)

**Comment by arunge** [comment]
Note for fixing:
- see: `leafletCRS()` in https://www.rdocumentation.org/packages/leaflet/versions/2.1.1/topics/leaflet
- https://stackoverflow.com/questions/56597938/how-can-i-use-and-understand-r-leaflets-crsclasses
- https://en.wikipedia.org/wiki/Equirectangular_projection

**Comment by arunge** [comment]
Fixing this issue is not trivial. Since I am using a function from the leaflet package here: `addCircles()`. The [documentation](https://www.rdocumentation.org/packages/leaflet/versions/2.1.1/topics/addControl) says point radius is defined in meters:
> radius  -  a numeric vector of radii for the circles; it can also be a one-sided formula, in which case the radius values are derived from the data (units in meters for circles, and pixels for circle markers)

What I found is, that there must be an issue with the default projection or crs class (https://www.rdocumentation.org/packages/leaflet/versions/2.1.1/topics/leaflet) that is used by this function. I was not able to figure out a solution.

Alternatively, I could use a different function to plot the points: `addCircleMarkers()`. However, then the radius will be fixed to the screen size and can only be given in terms of pixel. Zooming would not change the radius. Still it would be possible to adjust the radius with the slider.

@isomemo Should we go for this option?

**Comment by arunge** [comment]
As discussed today, I will exchange the function and use `addCicleMarkers()`, and update labels correspondingly.

**Comment by isomemo** [comment]
Ok!

**Comment by isomemo** [comment]
@arunge seems to be working fine in Beta version!
