### ISSUE TITLE
Bug in loading non-decimal coordinates

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/iso-app#62]
@arunge 

In the Pandora interface, we can select to upload coordinates in 3 different formats. See the image below:

![image](https://user-images.githubusercontent.com/46485054/193857890-8fc0ca04-40a9-4239-aa1e-b15016d4c405.png)

The second and third formats will include non-numerical values. This Excel file contains Latitude and Longitude fields using the second format:

[alkane_database.xlsx](https://github.com/Pandora-IsoMemo/iso-app/files/9708250/alkane_database.xlsx)

I uploaded this file via the Pandora interface and then selected the second coordinates format. However, I could not select the fields Latitude and Longitude to set the coordinates input. This is likely because the implementation excludes any fields with non-numeric entries and it does not take into account that we have different coordinate formats.

In the modelling section (e.g., model AverageR) we can also select one of the three coordinate formats. There the selection of the fields is working.

**Comment by arunge** [comment]
While fixing the bug with the columns, I extracted a new module (1) for the location fields:

![image](https://user-images.githubusercontent.com/16759098/194256361-9237d53e-94a0-4823-b0cc-ac1a0fc976aa.png)

- additionally the columns will be set automatically if a match was found.

However, I would like to apply this module also in the modelling tabs, but the user interface there is currently a bit different:
- coordinates are only available when "Upload file" is active (1)
- Lat/long is always available (2)

![image](https://user-images.githubusercontent.com/16759098/194257631-9754a9c4-5453-43e8-8438-6467573851de.png)

@isomemo  What is the best here?
Is it required to see Lat/Long input also for "database" source? Can I hide it here?

If I can hide it when "database" is selected, I could easily use the module from the data tab with the automatic default Lat/Long columns here.

**Comment by isomemo** [comment]
@arunge 

Yes, indeed for the modelling the lat/long inputs work differently. I have the following comments:

1) When it comes to hiding the fields if the database option is selected. What if we have a checkbox for that to show/hide? If the user selects database then the checkbox is set to hide but the user still has the option of activating it. I mention this since there could be situations where the database contains more than one pair of options for lat/long

2) Currently, I believe that the following applies to the modelling: 

if a data input contains lat/long cells which are empty or contain coordinates in the wrong format (depending on user selection) then the model is not run and the user is not informed of which rows are problematic.

Each model will have different imputes that need to be numeric. In this case, if a single cell is empty or contains non-numeric values the model will not be run and an error message given.

3) Instead of the above, I was thinking that a filter is applied that removes rows with empty cells or non-numeric values. This would apply to the following:

AverageR: Dependent variable; Uncertainty (this field is optional)
TimeR: Dependent variable; Uncertainty (this field is optional); Mean or lower time point; Standard deviation or upper time point (this field may be optional depending on user choice for Date type)
SpreadR: Mean or lower time point; Standard deviation or upper time point (this field may be optional depending on user choice for Date type)
KernelR: Presence/Absence (this field is optional); Weighting variable (this field is optional)
KernelTimeR: Mean or lower time point; Standard deviation or upper time point (this field may be optional depending on user choice for Date type); Presence/Absence (this field is optional); Weighting variable (this field is optional)

4) if rows are filtered out prior to the modelling (because of issues with lat/long and/or numeric fields) then a message is issued "Model run with X out of Y rows due to missing data and/or non-numeric values"

**Comment by arunge** [comment]
Regarding:
> When it comes to hiding the fields if the database option is selected. What if we have a checkbox for that to show/hide? If the user selects database then the checkbox is set to hide but the user still has the option of activating it. I mention this since there could be situations where the database contains more than one pair of options for lat/long

Would it then make sense to have this option (to set Lat/Long columns, optionally) also in the "data" section? Since the columns selected for lat/long in the data section are used in the interactive map section to show the points on the map. Maybe we could change this to be consistent within all sections? That is, also with database source one could select lat/long?

**Comment by isomemo** [comment]
@arunge in the case of the data section the user can choose to assign or not coordinates. You are now working on the new task of trying to guess (on the basis of the field name) what are the lat/long. However, this could fail and so the user will always have the option to select different fields.

In principle, I would like to have everything working in a consistent manner. However, for the modelling tab the situation is a bit different since there we know what are the lat/long fields coming from the database option (or simply there are no coordinates like for the 14Sea database). 

Overall, do you think it is worthwhile doing this type of changes for consistency? How much time would it consume? I am just wondering since this is mainly a aesthetical issue (and inputs are working, other than the issues mentioned previously with missing/wrong data) if it is worthwhile investing time on this.

**Comment by arunge** [comment]
@isomemo 

> However, this could fail and so the user will always have the option to select different fields.

Yes, if this happens the inputs will just be empty.

> ... (or simply there are no coordinates like for the 14Sea database).

The same here, the inputs just would be empty.

> Overall, do you think it is worthwhile doing this type of changes for consistency?

Since the app grew regarding the number of features, it is important to provide more structure to the code base. In the past, when the modelling development was the main task, the focus was less on the structure of inputs, outputs and reactives. Unfortunately, a lot of copy-paste was used for the different tabs that have common user-interfaces. This makes bug-fixing quite challenging. 
I would always recommend to introduce modules that encapsulate inputs that belong together semantically. And only apply the modules in all the different tabs, where the respective input is needed.
This prevents naming-conflicts, reduces the risk of bugs and (maybe the most important here) increases the readability of the code. By this, wrong (or missing) logic with updates of inputs/outputs can be detected more easily.

> How much time would it consume?

I already created the module, applying it to all the tabs maybe costs around two more hours. But we already have a task for that. This kind of restructuring belongs to: https://github.com/Pandora-IsoMemo/iso-app/issues/34.

> ... since this is mainly a aesthetical issue ...

What the user is seeing might be only aesthetical, but this improves the code base behind the scenes.

If you don't mind, I would replace the old inputs for lat/long with the new module and just hide the _coordinate format input_ where it is currently also hidden.
This possibly only changes the order of the inputs in a particular tab.

**Comment by arunge** [comment]
I merged a [new version](https://github.com/Pandora-IsoMemo/iso-app/pull/66#issue-1398179557) to the [beta app](https://isomemoapp.com/app/iso-memo-app-beta) that fixes this bug in the data tab. Additionally, now [default columns are set automatically](https://github.com/Pandora-IsoMemo/iso-app/issues/67).

Regarding the modelling tabs I had a look into the code. Currently the model starts running directly after the data upload.
This makes the application of the module tricky. I would like to discuss potential options tomorrow.

**Comment by arunge** [comment]
Discussed today regarding:
> Currently the model starts running directly after the data upload.

* Seems not to be the case with the beta version. I will check this issue.

* removing the feature to upload data in the modelling tab is not an option. Although, it would help to reduce redundancy (the user now can upload files over the pandora interface which was not possible in the past), users of the app might got used to the feature and could miss it.

- [ ] I will think about the current code structure and try to find a simple way to apply the new module. If the effort would be to large, we just keep the redundant but working code as it is. The bug mentioned above is already fixed.

**Comment by isomemo** [comment]
@arunge the beta and regular versions do not automatically run the model and this seems to be working fine. Yes, we should not invest too much time in this as this seems to be primarily an aesthetic issue. Better to prioritize bug fixing.
