### ISSUE TITLE
[MPI_tasks2022]: Pandora Isomemo - KernelTimeR and TimeR (~ 5 h)

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/iso-app#8]
Input box to select a specific time (as current in current input boxes for coordinate and zoom). Fix the current gif [export bug](https://github.com/INWT/mpi-iso-app/issues/223) in TimeR/KernelTimerR and add the option to export zip files containing the time slides as separate files (svg, png, pdf, tiff, geo-tiff). User options the same as with gif export but time slices as individual files (user can select jpg, tiff, png) saved in a zip file.

________________________________________________________________________________________________________
INWT Original Comments (August 21, 2021):
* [x]	Input Box: ~1 h
* [x] Zip Export: ~4 h
·   	export option will export raw data (not the plot) with resolution set by the user
·   	Gif export bug: for some reason the gif export is too resource intensive for the server, which breaks the functionality; we are in the process of identifying the reason for this issue and finding a strategy to limit resource consumption. 

Update (November 2, 2021): "export bug" is most probably a timeout issue on the server. Saving as separate images in zip should be quite straightforward (necessary to add zip command utility to docker image).

**Comment by arunge** [comment]
I am checking what needs to be done still:
- [x] Input box to select a specific time (as current in current input boxes for coordinate and zoom).

This looks to be ready:
![image](https://user-images.githubusercontent.com/16759098/183652586-364862e5-38b1-48c2-bde4-e3327364c592.png)

@isomemo Is this what you needed here?

**Comment by arunge** [comment]
- [x] Fix the current gif https://github.com/INWT/mpi-iso-app/issues/223 in TimeR/KernelTimerR

It takes some time, but the download is working:
![image](https://user-images.githubusercontent.com/16759098/183653131-717d4ebf-8b50-4f56-a3d1-bbbcf9936a9f.png)

As output I got a gif showing the plot for the selected steps. Seems to be fine.

@isomemo Do you still need the following option?

> - add the option to export zip files containing the time slides as separate files (svg, png, pdf, tiff, geo-tiff). User options the same as with gif export but time slices as individual files (user can select jpg, tiff, png) saved in a zip file.

**Comment by isomemo** [comment]
@arunge the highlighted option in 1 is a slider (not an input box). You will notice below that we have input boxes for coordinates (to be used as an alternative to the buttons to move map/zoom slider). Please add there an input box to select time (for KernelTimerR and TimeR).

As for the bug (point 2) this was also noticed by you previously. Can you please open the gif and check if it working? I would then do my own tests.

**Comment by arunge** [comment]
> Can you please open the gif and check if it working? I would then do my own tests.

The gif is working and showing (the default) 6 plots at time points 0, 1000, 2000, 3000, 4000, 5000.

**Comment by isomemo** [comment]
@arunge I think that this worked for you because the file was small. I tried this and hte app greyed out for KernetTimeR (same happening for TimeR) before producing the gif. I did the following:

1) Loaded the LiVES data via the IsoMemo skin
2) Run a KernelTimeR model with lower time point as dateLower and upper time point as dateUpper
3) The model worked fine. Then I tried to export a big between 0 and 8000 (with reverse time order) and 100 as the time interval
4) the Generating gif time tracker ran until 0 and then the app crashed

**Comment by arunge** [comment]
New input box  for the time is under review (#57).

**Comment by arunge** [comment]
> I think that this worked for you because the file was small. I tried this and hte app greyed out for KernetTimeR

I can confirm this issue. The app crashed also locally for smaller time intervals. I am checking the options here.

**Comment by arunge** [comment]
@isomemo  With [version 22.09.01](https://github.com/Pandora-IsoMemo/iso-app/blob/beta/NEWS.md) the [input box](https://github.com/Pandora-IsoMemo/iso-app/pull/57#issue-1334665197) is on the [beta](https://isomemoapp.com/app/iso-memo-app-beta) for testing.

The [zip option](https://github.com/Pandora-IsoMemo/iso-app/pull/58#issue-1337030661) is under review.

**Comment by arunge** [comment]
Feedback regarding the [input box](https://github.com/Pandora-IsoMemo/iso-app/pull/57#issue-1334665197)
- the update of the map is very slow
- better use a button instead of reactive updates
- should be executed after setting lat/long
- [ ] find a useful position for the button

**Comment by isomemo** [comment]
@arunge just a small correction. The update to time should be done at the same time as for coordinates. However, if input boxes are blank previous values selected in the map remain the same. For instance, if I only input time but not coordinates nor zoom then there would be no change for the coordinates/zoom but only for time. Finally, please remember that this applies to both the TimeR and KernelTimeR models.

**Comment by arunge** [comment]
I pushed a [new version 22.09.3](https://github.com/Pandora-IsoMemo/iso-app/pull/58) to the [beta branch](https://isomemoapp.com/app/iso-memo-app-beta) that will be available after tests are completed. @isomemo Feel free to test it. :slightly_smiling_face: 

I did not check this task:
> - export option will export raw data (not the plot) with resolution set by the user

Is it already there and working? Or must it be implemented?

The changes regarding
> The update to time should be done at the same time as for coordinates. However, if input boxes are blank previous values selected in the map remain the same. For instance, if I only input time but not coordinates nor zoom then there would be no change for the coordinates/zoom but only for time. Finally, please remember that this applies to both the TimeR and KernelTimeR models.

are still in progress.

**Comment by arunge** [comment]
@isomemo With [version 22.10.3](https://github.com/Pandora-IsoMemo/iso-app/pull/61#issue-1387861933) on the [beta app](https://isomemoapp.com/app/iso-memo-app-beta) I restructered the UI for zooming, lat/long (and time) in all modelling tabs. Now, one must press a button to set time, lat/long or zoom. Please, test the new UI and let me know if all works as expected. 

Since, this was a more complex restructering that was necessary for all modelling tabs, this is a part of the new task ["Restructure (split up) scripts for modeling tabs"](https://github.com/Pandora-IsoMemo/iso-app/issues/69).

---
Regarding
> - export option will export raw data (not the plot) with resolution set by the user

Currently, there are buttons for
- "Export Plot"  to export `jpg, pdf, svg, tiff, geo-tiff` for a given width / height in pixel and
- "Export Data" for `csv, xlsx, json`.

Which raw data should be exported additionally and what kind of _resolution_ do you mean?

**Comment by isomemo** [comment]
@arunge this should be implemented for TimeR and KernelTimeR and applies to the temporal plots. I tested this for both models using LiVES data. See images below:

![image](https://user-images.githubusercontent.com/46485054/205272407-e1f9b160-e9ee-4421-8e6b-2067e59db96b.png)

![image](https://user-images.githubusercontent.com/46485054/205273406-70caffea-fb41-4ca7-a5d5-bb73a0ac6dff.png)

The options seem correct! I suppose that "Time interval..." are the intervals at which the graphs is sampled? If so this is how it should work. The output file should include mean plus all options under estimation type in separate columns. However, when I press the button "Export" shown in figure a new tab is created but no give is given for download.

**Comment by arunge** [comment]
You are right, I tested this only with the map, which is working, but there seems to be an issue with the time plotting function.

**Comment by arunge** [comment]
I fixed the issue.
However, I am a bit confused:
- for **Map**: the time series is a series of plots for a given `time`, exactly that time parameter which is set with the time slider, so above settings generates 6 maps for the time points 0, 1000, 2000, 3000, 4000, 5000
- for **Time course** (as the example above): the `time` parameter is currently not used since a time plot already shows all possible time points (if I understand that correctly) -> currently a series contains always the same **time course** plot

> I suppose that "Time interval..." are the intervals at which the graphs is sampled?

Currently the model is **not** recalculated to generate the series. The plot is only created dependent on the given time using the same model output.

@isomemo Should we hide this option for **Time course** plots? Or what kind of series should be generated in that case? 
We have the _time range slider_ here. Should somehow different time ranges be used for the time series?

**Comment by arunge** [comment]
@isomemo  with [version 22.12.3](https://github.com/Pandora-IsoMemo/iso-app/pull/85#issue-1503547462) on the [isomemo beta app](https://isomemoapp.com/app/iso-memo-app-beta) the option to create a time series in export of plots will be hidden for time course plots.
