### ISSUE TITLE
No Coordinate fields for Time course plot in TimeR 

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/iso-app#94]
For the attached dataset, there are no fields in Timer where to input coordinates with the aim of generating local time course plots. Actually, part of the options that are related to the map plot still remain in their position, when they were supposed to disappear. They are in fact not applicable to the timecourse plot.

I have used version 22.12.3 offline. I am not aware if there is now a different system to implement coordinates, but I can't find it.
However, I don't think this is a bug that is dataset- or options-related. Likely also KernelTimeR has the same problem.

Anyway I have employed the following options:

Dependent variable: IRMS δ13C Collagen
Uncertainty(optional) of dep. var.: IRMS δ13C Collagen unc
Date type: Interval
Mean or lower time point: Min. Year (95%)
Standard deviation or upper time point: Max. Year (95%)
Longitude variable: Longitude
Latitude variable: Latitude
Site/ID (optional): Site Name

Smooth Type: Planar
no border correction for pacific
Number of spatial basis functions: 250
Extrapolation behaviour: Linear
no Remove model outliers
no Remove data outliers
no Restrict model area
yes Bayesian model
no Varying standard error

Distribution of date uncertainty: normal (sd = 1/4 width)
Number of MCMC iterations: 5000
Number of burnin iterations: 1000
Number of MCMC chains: 1
MCMC thinning (keep every x-th sample): 10
Amount of smoothing: 1
no Fix colours and ranges

@arunge 

[ROman and medieval Italy.xlsx](https://github.com/Pandora-IsoMemo/iso-app/files/10547788/ROman.and.medieval.Italy.xlsx)

**Comment by arunge** [comment]
@isomemo @CarloCocozza  Sorry, but this was my fault. I updated the UI of Lat/Long inputs when adding the option to set decimal places for center estimates.
It was meant to be a feature: Since there are so many input fields in the modelling tabs, I wanted to hide some if they are not needed. However, I have missed that the inputs for Lat/Long are going into the plotting function of the time plot. I am removing the condition to hide the inputs and fixing this on both versions. I will notify you when its done. Thanks for your patience and sorry for any inconveniences!

**Comment by arunge** [comment]
@isomemo @CarloCocozza 
I fixed the issue on iso-app main with [version 22.12.3.1](https://github.com/Pandora-IsoMemo/iso-app/pull/95) and on iso-app beta with version 23.01.4.1

**Comment by CarloCocozza** [comment]
@arunge Thanks! 

For the offline version, do I need to install isomemo again to obtain the last version?

**Comment by arunge** [comment]
@CarloCocozza Yes, only with version 22.12.3.1 (main app) or version 23.01.4.1 (beta app) or higher this bug is fixed.

When using docker you have to 
- pull the newest version with (https://github.com/Pandora-IsoMemo/iso-app/wiki/Getting-Started#download-and-install-docker-image):
```
docker pull ghcr.io/pandora-isomemo/iso-app:main
```
- and run it with (https://github.com/Pandora-IsoMemo/iso-app/wiki/Getting-Started#start-the-application):
```
docker run -p 3838:3838 ghcr.io/pandora-isomemo/iso-app:main
```
If wished, you can get the beta version by using `:beta` instead of `:main`.

In case you have already an app running you will receive the error
```"Docker - container port is already allocated"```
Please follow the steps here (in your terminal) to remove the running app: https://github.com/Pandora-IsoMemo/drat/wiki/FAQ#docker---container-port-is-already-allocated
